version: 0.2

phases:
  pre_build:
    commands:
      - set -x 
  build:
    commands:
      - sam build -b ./build -m ./requirements.txt
      - mv ./build/ServiceApiFunction/* ./src/
      - rm -rf ./build
      - sam package --template-file template.yaml --use-json --s3-bucket ${STACK_BUCKET_NAME} --s3-prefix ${STACK_NAME} --output-template-file built_template.json
      - sam deploy --template-file built_template.json --stack-name ${STACK_NAME} --capabilities CAPABILITY_IAM
      - echo "Done!"
